### ISSUE TITLE
Newlines not respected on code blocks

### ISSUE THREAD

**Issue by debdutdeb** [RocketChat/fuselage#718]
### Environment Information:

- Rocket.Chat Server Version: open (so 4.7 I'm guessing)
- Rocket.Chat App Version: 4.26.1.30852
- Device Name: poco m4
- OS Version: android 11

### Steps to reproduce:

1. send a message in triple backticks with a linebreak

```
\`\`\`
like
this
\`\`\`
```

(How do I escape backticks in md? :P)

### Expected behavior:

```
like
this
```

### Actual behavior:

![IMG_20220510_184053.jpg](https://user-images.githubusercontent.com/76006232/167636482-6b934f48-3146-48d4-b77d-662c50e87de9.jpg)

### Additional context:

web client is working as expected

**Comment by gabriellsh** [comment]
> Rocket.Chat App Version: 4.26.1.30852
> web client is working as expected
> transferred this issue from RocketChat/Rocket.Chat.ReactNative [on 10 May](https://github.com/RocketChat/fuselage/issues/718#event-6582290154)

Since web client is working as expected, this should not be an issue. Also, I think the mobile app still uses the old parser (which is implemented directly into the core app).

Btw, I'm considering you opened this issue here because this is where the repo is where the `message-parser` lives. Even though that's true, the `message-parser` project only converts raw text into an AST object, meaning the rendering is detached from the parsing step. This means it's more likely this issue related to rendering than parsing.

I'll close this for now, but if you think it still makes sense for this to be an issue, please, reopen it and add more context.
