### ISSUE TITLE
Unable to run ui-kit/playground

### ISSUE THREAD

**Issue by sanket1726** [RocketChat/fuselage#947]
**Description**

**Steps to reproduce**

**Insert an image/gif**

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this issue because we moved the ui-kit playground to Rocket.Chat monorepo (https://github.com/RocketChat/Rocket.Chat/pull/29339) and it's running normally.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
