### ISSUE TITLE
fuselage: build script failing

### ISSUE THREAD

**Issue by Rec0iL99** [RocketChat/fuselage#986]
**Description**
I'm trying to setup fuselage on my local machine for contributing. I'm unable to proceed further than the build setup mentioned in the [contributing to fuselage docs](https://developer.rocket.chat/fuselage/contributing#how-to-build-your-project).

**Steps to reproduce**

After forking the repo and cloning I ran the following scripts at the root (`/fuselage`):

```bash
// I deleted the local yarn.lock file to get a fresh yarn.lock since yarn install was failing at first
yarn && yarn build -> failing at the build script
```

Here's my [pastebin error log](https://pastebin.pl/view/4ecdcf43).

**Insert an image/gif**

For testing I tried running the `uikit-playground` package and it's unable to resolve the local npm deps from the mono-repo:

<img width="1040" alt="Screenshot 2023-02-20 at 12 47 49 PM" src="https://user-images.githubusercontent.com/56463684/220038036-627ea548-134e-4f7f-9ab4-2faca4e7be77.png">

**Comment by ananthastaputra** [comment]
Hey @Rec0iL99, I am also here for contributing to fuselage, I have setup the build in my local machine and its perfectly running  fine in my machine, I would like to point out few things here.
1) cloning the repo 
2) installing node modules at root level
3)yarn build
4) navigate to packages/fuselage/
5) yarn storybook

yarn start simply wont start since this is based on storybook, you can give `yarn storybook` to run the project.

**Comment by Rec0iL99** [comment]
Hi @ananthastaputra, thanks for reaching out. The problem for me is `yarn build` (at the root level specifically at `fuselage` package) is failing for me (you can check my error logs). Maybe it could be a problem with my machine. 

If it is working for you, please share your `node`, `npm` and `yarn` versions. Did you run `yarn build` at the root or `fuselage/` level?

**Comment by ananthastaputra** [comment]
Yes we have to build at root level, I dont think its due to yarn, npm, node versions anyhow 
<img width="1436" alt="Screenshot 2023-03-02 at 9 17 00 PM" src="https://user-images.githubusercontent.com/63888555/222479455-f5925064-8698-48ad-ba1e-d1fb68df35cd.png">

You can observe that I came back from packages and done `yarn install`, I am mentioning my npm and yarn versions here.


yarn -->3.2.4
npm --> 8.19.3

**Comment by Rec0iL99** [comment]
`yarn install` is working perfectly for me. It's `yarn build` that's failing :(

Did you run `build` script at root level?

**Comment by Rec0iL99** [comment]
@ananthastaputra please let me know your Rocket.Chat username. We can discuss there.
